services:
    damjanko-api:
        container_name: damjanko-api
        build:
            context: ./damjanko-api
            dockerfile: Dockerfile
        volumes:
            - './damjanko-api:/app'
            - '/app/node_modules'
        ports:
            - 6661:3000
    damjanko-spa:
        container_name: damjanko-spa
        build:
            context: ./damjanko-spa
            dockerfile: Dockerfile
        volumes:
            - './damjanko-spa:/app'
            - '/app/node_modules'
        ports:
            - 3002:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    damjanko-backoffice:
        container_name: damjanko-back-office
        build:
            context: ./damjanko-back-office
            dockerfile: Dockerfile
        volumes:
            - './damjanko-back-office:/app'
            - '/app/node_modules'
        ports:
            - 3003:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
